update security.md
PsychOps/serverpinger pull request #62
Opened 2023-12-17 01:09 UTC by Soapy7261

i should probably also change the email but idk what the correct email is :c

2023-12-24 10:34 UTC, MiataBoy requested changes

2023-12-24 10:34 UTC, MiataBoy commented on SECURITY.md
>  - Sending a mail to [joshuaslui0203@gmail.com](mailto:joshuaslui0203@gmail.com)
```suggestion
- Sending a mail to [support@wolfsvale.tech](mailto:support@wolfsvale.tech)
```

2023-12-26 01:13 UTC, Soapy7261 commented
k

2023-12-29 07:09 UTC, Soapy7261 commented
please :pray:

2023-12-29 16:17 UTC, MiataBoy commented
CodeQL just doesn't know what to do anymore

2023-12-29 16:17 UTC, merged