Translations into V4
PsychOps/serverpinger pull request #72
Opened 2024-08-01 01:12 UTC by Soapy7261

WIP

2024-08-01 01:19 UTC, Soapy7261 commented
yay pylint doesn't hate me anymore!

2024-08-08 20:42 UTC, MiataBoy commented
Do you have an ETA on this pull request @Soapy7261?

2024-08-08 21:17 UTC, Soapy7261 commented
I mean i kinda want your feedback on what to add, it *could* already be added

2024-08-08 23:49 UTC, MiataBoy requested changes
This seems fine to me. I haven't tested it yet and i don't see the need to because the code is clearly functional. Though I'd like to ask that you **add indentation between each respective function and test**, because this looks a bit awkward otherwise.

I will most likely mend the code after it is pushed to work with user/guild database settings, but that should not take much work with an understanding of Rebel's systems. You can mark this as ready for review after changing the indentation if you wish, and then i will pull it.

2024-08-09 00:07 UTC, Soapy7261 commented
That should be what you want, right?

2024-08-09 00:34 UTC, MiataBoy requested changes

2024-08-09 00:34 UTC, MiataBoy commented on providers/translation/get_translate.py
> +    def get_translation(self, language: str, message_code: str) -> str:
Missing empty line

2024-08-09 12:04 UTC, MiataBoy approved these changes

2024-08-09 12:05 UTC, merged